# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DevFestMN 2016"
email: "info@devfest.mn"
description: "DevFestMN is a Google Developer Group - Twin Cities hosted technology event."
baseurl: ""
url: "https://devfest.mn"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-XXX-5"
googleAnalyticsSiteUrl: "devfest.mn"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Google Developer Group - Twin Cities"
organizerAlternateName: "Google Developer Group - Twin Cities"
organizerDescription: "Vibrant and active volunteer-ran group focued on Google technologies."
organizerEmail: "cledwyn@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgtc.com/"

# Head
metaKeywords: "event, gdg, devfest, devfestmn, gdgtc, google, programming, android, chrome, IoT, developers, schulze"
twitterAccount: "@DevFestMN"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevFestMN 2016 | <typeout>"
eventDate: "February 6, 2016"
typeoutTextValues: '"", "Android", "Chrome", "IoT", "Design"'
typeoutFallback: "  "
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About DevFestMN"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Huge developer oriented tech event in the MidWest and Twin Cities! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Workshops, hands-on experience, hacking and debugging. Come and tame your favorite technology or topic!" }
 - {title: "After Party", image: "hackathon.jpg", text: "Casual and fun sponsor-hosted after party where you can mingle, have a drink, and meet the speakers." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "250", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "8", specialCharacter: "+", info: "hours", detail: "of pure technology fun"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "5", specialCharacter: "", info: "amazing tracks", detail: "plus an afterparty"}

# Latest News Block
latestNewsTitle: "Latest News"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "University of St. Thomas - Schulze Hall"
eventLocationLink: "https://www.google.com/maps/place/University+of+St.+Thomas+-+Opus+College+of+Business/@44.9745667,-93.2767806,14z/data=!4m5!1m2!2m1!1sschulze+hall!3m1!1s0x52b332942e2c9481:0x624b1a38a350d4d1"
eventStreetAddress: "1000 Lasalle Ave"
eventAddressLocality: "Minneapolis"
eventAddressLocalityRegion: "MN"
eventPostalCode: "55403"
eventAddressCountry: "USA"
eventStartTime: "2016-02-06T08:00"
eventDoorTime: "08:00"
eventEndTime: "2016-02-06T17:00"
eventPlaceCoordinates: "44.9745667,-93.2767806"
mapCenterCoordinates: "44.9745667,-93.2767806"
mapMobileCenterCoordinates: "44.9745667,-93.2767806"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "University of St. Thomas - Schulze Hall"
venueFeatures: ["Great Venue", "Large Auditorium", "Easy Parking"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfestmn"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for Updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around December. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets vailde for all day conference event and include snacks, lunch and after-party access."
ticketsOffers:
 -
  name: "Early Bird"
  price: "$20"
  priceCurrency: ""
  ticketsNumber: "50"
  ribbon: "-33.33%"
  buyButtonLink: "http://eventbrite.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2016-08-25T10:00"
  validThrough: "2015-09-30T23:59"
 -
  name: "Last Chance"
  price: "$TBD"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "$TBD"
  priceCurrency: ""
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+Gdgtc/posts", icon: "google-plus"}
 - {link: "https://twitter.com/gdgtc", icon: "twitter"}
 - {link: "https://facebook.com/GDGTC", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgtc.com/#home", text: "GDGTC.com"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest News"
blogCommentsEnabled: true
discusShortName: "devfestmn"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About Us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flights"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Getting Around Minneapolis"
directionDetailsCards:
 - {title: "From the Airport", information: 'The conference is approximately 30 minutes north-west from the Minneapolis St. Paul International Airport.'}
 - {title: "Public Transit", information: 'Taxis, bus services and light rails are all safe methods of travel. Uber and Uber Pool are also highly recommended.'}
 - {title: "Parking", information: 'The City of Minneapolis Parking Ramp at 11th Street & Harmon Place allows for hourly parking for visitors, faculty, staff and students. The entrance and exit to the ramp is on 11th Street, just west of Harmon Place. Street parking is also avaialble..'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://doubletree3.hilton.com/en/hotels/minnesota/doubletree-suites-by-hilton-hotel-minneapolis-MSPLSDT/index.html", text: "Doubletree Suites by Hilton Minneapolis"}
     - {link: "http://minneapolis.hyatt.com/en/hotel/home.html", text: "Hyatt Regency Minneapolis"}
     - {link: "http://www.lemeridienchambers.com/", text: "Le Méridien Chambers Minneapolis"}
     - {link: "http://www3.hilton.com/en/hotels/minnesota/hilton-minneapolis-MSPMHHH/index.html", text: "Hilton Minneapolis"}
   -
    title: "Nearby Restaurants"
    links:
     - {link: "http://the-local.com/", text: "The Local (Irish)"}
     - {link: "http://barriotequila.com/", text: "Barrio (Latin)"}
     - {link: "http://www.hellskitcheninc.com/", text: "Hell's Kitchen (Breakfast & Eclectic)"}
     - {link: "http://pizzaluce.com/", text: "Pizza Luce (Italian)"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
